GET http://localhost:7777

###
GET http://localhost:7777/bye
###
POST http://localhost:7777 HTTP/1.1
Content-Type: text/css

Alok
###
POST http://localhost:7777/bye HTTP/1.1
Content-Type: text/css

Alok

